services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    working_dir: /app/backend
    command: ["node", "dist/app.js"]
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URL=${MONGODB_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend:/app/backend
    # depends_on:
    #   - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    environment:
      - NODE_ENV=production
      - VITE_HTTP_ENDPOINT=${VITE_HTTP_ENDPOINT}
      - VITE_SOCKET_ENDPOINT=${VITE_SOCKET_ENDPOINT}
      - VITE_JWT_SECRET=${VITE_JWT_SECRET}
    working_dir: /app/frontend
    command: ["npx", "serve", "-s", "dist", "-l", "80"]
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend